version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - bytebank-network

  transactions:
    build:
      context: .
      dockerfile: apps/transactions/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3000
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - NEXTAUTH_SECRET=bytebank-secret-troque-em-producao
    depends_on:
      - api
    networks:
      - bytebank-network

  host:
    build:
      context: .
      dockerfile: apps/host/Dockerfile
      args:
        TRANSACTIONS_URL: http://localhost:3001
        NEXT_PUBLIC_API_URL: http://localhost:3000
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=production
      - NEXTAUTH_SECRET=bytebank-secret-troque-em-producao
      - NEXTAUTH_URL=http://localhost:3002
    depends_on:
      - api
      - transactions
    networks:
      - bytebank-network

networks:
  bytebank-network:
    driver: bridge