services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - bytebank-network

  api:
    build:
      context: ./api
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/bytebank
    depends_on:
      - mongo
    networks:
      - bytebank-network

  transactions:
    build:
      context: .
      dockerfile: apps/transactions/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3000
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - NEXTAUTH_SECRET=bytebank-secret-troque-em-producao
      - API_URL=http://api:3000
    depends_on:
      - api
    networks:
      - bytebank-network

  host:
    build:
      context: .
      dockerfile: apps/host/Dockerfile
      args:
        TRANSACTIONS_URL: http://transactions:3001
        NEXT_PUBLIC_API_URL: http://localhost:3000
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=production
      - NEXTAUTH_SECRET=bytebank-secret-troque-em-producao
      - NEXTAUTH_URL=http://localhost:3002
      - API_URL=http://api:3000
    depends_on:
      - api
      - transactions
    networks:
      - bytebank-network

volumes:
  mongo-data:

networks:
  bytebank-network:
    driver: bridge
